export type CatalogDecision = {
  id: string;
  group: string;
  title: string;
  ask: string;
  hints: string[];
  when: string;
};

/** What coordinators actually collect — not “pick a venue.” */
export const PLANNER_DECISIONS: CatalogDecision[] = [
  {
    id: "first-look",
    group: "The day",
    title: "First look?",
    ask: "Do you see each other before the ceremony?",
    hints: ["Yes — more photo time, calmer aisle", "No — keep the aisle moment", "Private vow read instead"],
    when: "Before you lock photography hours",
  },
  {
    id: "getting-ready",
    group: "The day",
    title: "Getting ready",
    ask: "Together, apart, or same hotel different rooms?",
    hints: ["Apart (classic)", "Together", "Same venue, separate rooms"],
    when: "Affects hair/makeup call times",
  },
  {
    id: "ceremony-time",
    group: "The day",
    title: "Ceremony start",
    ask: "What time do guests sit?",
    hints: ["Late morning", "Afternoon", "Evening"],
    when: "Drives every other timestamp",
  },
  {
    id: "cocktail-where",
    group: "The day",
    title: "Cocktail hour",
    ask: "Where do guests go after the ceremony?",
    hints: ["Same room, flip", "Terrace / lawn", "Separate lounge"],
    when: "Venue walk-through",
  },
  {
    id: "hard-stop",
    group: "The day",
    title: "Hard stop",
    ask: "When does music have to die?",
    hints: ["Venue curfew", "City noise ordinance", "We control the building"],
    when: "Before you book a band",
  },
  {
    id: "after-party",
    group: "The day",
    title: "After-party",
    ask: "Does the night continue somewhere else?",
    hints: ["No", "Hotel bar", "Second venue", "House"],
    when: "Transportation + last dance",
  },
  {
    id: "rain-plan",
    group: "Weather & place",
    title: "Rain plan",
    ask: "If it pours, where is the ceremony?",
    hints: ["Indoor room already held", "Tent", "Covered porch", "Umbrellas and pray"],
    when: "Before invitations go out",
  },
  {
    id: "in-or-out",
    group: "Weather & place",
    title: "In or out",
    ask: "Ceremony outdoors, reception in, or the reverse?",
    hints: ["Both out", "Both in", "Out then in", "In then out"],
    when: "Venue type",
  },
  {
    id: "load-in",
    group: "Weather & place",
    title: "Vendor load-in",
    ask: "How early can florals, DJ, and cake enter?",
    hints: ["Morning of", "Night before", "Ask the venue"],
    when: "Coordinator packet",
  },
  {
    id: "kids",
    group: "People",
    title: "Kids",
    ask: "Are children at the ceremony, the reception, both, or neither?",
    hints: ["All ages", "Ceremony only", "Reception only", "Adults only"],
    when: "Before save-the-dates",
  },
  {
    id: "plus-one-rule",
    group: "People",
    title: "Plus-ones",
    ask: "Who gets a plus-one? Married / living together / wedding party / everyone?",
    hints: ["Married or living together", "Wedding party too", "Everyone 18+", "Named only"],
    when: "Guest list",
  },
  {
    id: "party-size",
    group: "People",
    title: "Wedding party size",
    ask: "How many people stand with you?",
    hints: ["Just a witness", "2–4", "Full party"],
    when: "Attire + processional",
  },
  {
    id: "who-walks",
    group: "People",
    title: "Who walks whom",
    ask: "Processional order — parents, party, you.",
    hints: ["Traditional", "Both partners walk", "Write our own"],
    when: "Run of show",
  },
  {
    id: "family-photos",
    group: "People",
    title: "Must-have family photos",
    ask: "List the groupings so the photographer isn’t guessing.",
    hints: ["Immediate only", "Grandparents too", "Write a shot list"],
    when: "Before the day",
  },
  {
    id: "unplugged",
    group: "People",
    title: "Unplugged ceremony",
    ask: "Phones down until you say so?",
    hints: ["Yes, sign at the door", "No restriction", "No flash only"],
    when: "Programs / officiant",
  },
  {
    id: "meal-style",
    group: "Food & drink",
    title: "How people eat",
    ask: "Plated, buffet, stations, or family-style?",
    hints: ["Plated", "Buffet", "Stations", "Family-style"],
    when: "Catering tasting",
  },
  {
    id: "bar",
    group: "Food & drink",
    title: "The bar",
    ask: "Open, beer-and-wine, cash, or a signature plus beer and wine?",
    hints: ["Full open", "Beer, wine, one cocktail", "Beer and wine", "No alcohol"],
    when: "Budget + venue rules",
  },
  {
    id: "cake",
    group: "Food & drink",
    title: "Cake or dessert",
    ask: "Tiered cake, sheet + display, or a dessert table?",
    hints: ["Classic cake", "Small display + sheet", "Dessert table", "Skip — late-night only"],
    when: "Baker lead time",
  },
  {
    id: "late-night",
    group: "Food & drink",
    title: "Late-night food",
    ask: "Something after dancing, or guests leave hungry?",
    hints: ["Pizza / tacos", "Passed snacks", "None"],
    when: "Catering add-on",
  },
  {
    id: "vendor-meals",
    group: "Food & drink",
    title: "Vendor meals",
    ask: "How many hot meals for photo, video, DJ, planner?",
    hints: ["Ask each contract", "Budget 6–10", "Venue includes them"],
    when: "Final headcount",
  },
  {
    id: "officiant",
    group: "Ceremony",
    title: "Who marries you",
    ask: "Faith leader, friend ordained, or civil officiant?",
    hints: ["Faith", "Friend", "Civil / courthouse first"],
    when: "Early — their calendar",
  },
  {
    id: "vows",
    group: "Ceremony",
    title: "Vows",
    ask: "Traditional, written, or a mix?",
    hints: ["Traditional", "We write them", "Private vows + short public"],
    when: "Month-of",
  },
  {
    id: "unity",
    group: "Ceremony",
    title: "Unity moment",
    ask: "Candle, sand, handfasting, none?",
    hints: ["None", "Candle", "Cultural ritual", "Something we invent"],
    when: "Officiant meeting",
  },
  {
    id: "readings",
    group: "Ceremony",
    title: "Readings",
    ask: "Who reads, and what?",
    hints: ["None", "One friend", "Two — faith + poem"],
    when: "Programs",
  },
  {
    id: "photo-vs-video",
    group: "Photo & music",
    title: "Photo vs video",
    ask: "If the budget is tight, which do you protect?",
    hints: ["Photo first", "Video first", "Both, cut elsewhere"],
    when: "Priorities",
  },
  {
    id: "must-shots",
    group: "Photo & music",
    title: "Must-have shots",
    ask: "Three photos you will be sad to miss.",
    hints: ["Write them", "Give the photographer a list"],
    when: "Handoff",
  },
  {
    id: "first-dance",
    group: "Photo & music",
    title: "First dance",
    ask: "Which song, and do you want a lesson?",
    hints: ["We have the song", "Need suggestions", "Skip — join the floor"],
    when: "DJ cue sheet",
  },
  {
    id: "parent-dances",
    group: "Photo & music",
    title: "Parent dances",
    ask: "Both, one, combined, or none?",
    hints: ["Both", "Combined", "None"],
    when: "DJ + feelings",
  },
  {
    id: "do-not-play",
    group: "Photo & music",
    title: "Do-not-play",
    ask: "Songs that must never happen.",
    hints: ["Write a list", "Genre bans", "Trust the DJ"],
    when: "Music handoff",
  },
  {
    id: "send-off",
    group: "Guest experience",
    title: "Send-off",
    ask: "Sparklers, petals, bubbles, just leave?",
    hints: ["Sparklers (check fire rules)", "Petals / bubbles", "None — last dance and go"],
    when: "Venue + photo",
  },
  {
    id: "favors",
    group: "Guest experience",
    title: "Favors",
    ask: "Something to take home, or skip?",
    hints: ["Skip", "Edible", "Useful", "Donation in their name"],
    when: "Budget leftovers",
  },
  {
    id: "guestbook",
    group: "Guest experience",
    title: "How they leave a note",
    ask: "Book, audio, polaroid wall, none?",
    hints: ["Classic book", "Polaroid + album", "Audio guestbook", "Skip"],
    when: "Stationery / DIY",
  },
  {
    id: "welcome-bags",
    group: "Guest experience",
    title: "Welcome bags",
    ask: "Hotel bags for out-of-towners?",
    hints: ["Yes", "Note only", "No"],
    when: "Hotel block",
  },
  {
    id: "hotel-block",
    group: "Guest experience",
    title: "Hotel block",
    ask: "One hotel, two price points, or none?",
    hints: ["One block", "Nice + cheaper", "Guests book themselves"],
    when: "Travel page",
  },
  {
    id: "shuttle",
    group: "Guest experience",
    title: "Getting people there",
    ask: "Shuttle, parking, or they figure it out?",
    hints: ["Shuttle hotel → venue", "Valet / lot", "Rideshare"],
    when: "Travel + budget",
  },
  {
    id: "who-pays",
    group: "Money & legal",
    title: "Who pays what",
    ask: "You two, parents, split by category?",
    hints: ["We pay", "Parents contribute X", "Split by envelope"],
    when: "Budget seed",
  },
  {
    id: "license",
    group: "Money & legal",
    title: "Marriage license",
    ask: "When and where will you get it?",
    hints: ["County clerk this month", "Need an appointment", "Don’t know yet"],
    when: "30 days out (varies)",
  },
  {
    id: "name-change",
    group: "Money & legal",
    title: "Names after",
    ask: "Anyone changing a name? Hyphen, keep, new?",
    hints: ["No change", "One of us", "Both / hyphen"],
    when: "After the license",
  },
  {
    id: "insurance",
    group: "Money & legal",
    title: "Event insurance",
    ask: "Venue require it? Are you buying it anyway?",
    hints: ["Venue requires", "We’ll buy it", "Skipping"],
    when: "After venue contract",
  },
];

export const DECISION_GROUPS = Array.from(new Set(PLANNER_DECISIONS.map((d) => d.group)));
