import type { WeddingShape } from "./shape";

export type ShapeItem = { phase: string; title: string };

export const SHAPE_STARTERS: Record<WeddingShape, ShapeItem[]> = {
  us: [
    { phase: "now", title: "Learn the license rules for this county" },
    { phase: "now", title: "Decide who we tell, and when" },
    { phase: "now", title: "Book a photographer — or a trusted friend" },
    { phase: "now", title: "Name the witness if the county needs one" },
    { phase: "now", title: "Rings, if we want them that day" },
    { phase: "2-3", title: "Write vows, or decide we won’t" },
    { phase: "2-3", title: "Book dinner, a picnic, or nothing after" },
    { phase: "2-3", title: "Who files the license after we sign" },
    { phase: "1", title: "Tell the people who should hear it from us" },
    { phase: "week", title: "Confirm photographer and weather backup" },
    { phase: "week", title: "What we wear — and where we stand" },
    { phase: "after", title: "Confirm the license was filed" },
    { phase: "after", title: "Write the announcement for everyone else" },
    { phase: "after", title: "Thank the witness and the photographer" },
    { phase: "after", title: "Thank-you notes for gifts that arrive (90 days)" },
  ],
  small: [
    { phase: "12-18", title: "Set a total budget and who contributes" },
    { phase: "12-18", title: "Write down the top three priorities" },
    { phase: "12-18", title: "Pick a date (or a few options)" },
    { phase: "12-18", title: "Book one room that holds everyone" },
    { phase: "12-18", title: "Book photographer" },
    { phase: "12-18", title: "Start a guest-list draft" },
    { phase: "9-11", title: "Book officiant" },
    { phase: "9-11", title: "Decide food: restaurant, caterer, or potluck" },
    { phase: "6-8", title: "Create a wedding website" },
    { phase: "6-8", title: "Open a registry — or decide you won’t" },
    { phase: "4-5", title: "Send invitations (RSVP about a month before)" },
    { phase: "4-5", title: "Track RSVPs as they come in" },
    { phase: "2-3", title: "Draft the seating chart" },
    { phase: "2-3", title: "Write vows" },
    { phase: "2-3", title: "Apply for the marriage license" },
    { phase: "2-3", title: "Order thank-you cards" },
    { phase: "1", title: "Give final guest count to vendors" },
    { phase: "1", title: "Finalize seating and meals" },
    { phase: "week", title: "Reconfirm every vendor" },
    { phase: "after", title: "Send thank-you notes (aim for 3 months)" },
    { phase: "after", title: "Review and choose photos" },
    { phase: "after", title: "Leave vendor reviews" },
  ],
  weekend: [],
  two: [
    { phase: "now", title: "Learn the license rules for this county" },
    { phase: "now", title: "Set the marrying date and the gathering date" },
    { phase: "now", title: "Book a photographer for the marrying day" },
    { phase: "now", title: "Decide who is at the first day" },
    { phase: "2-3", title: "Who files the license after we sign" },
    { phase: "week", title: "Confirm the marrying-day plan" },
    { phase: "after", title: "Confirm the license was filed" },
    { phase: "12-18", title: "Book the gathering room" },
    { phase: "9-11", title: "Start a guest-list for the gathering" },
    { phase: "6-8", title: "Create a wedding website — invitation, not RSVP yet" },
    { phase: "4-5", title: "Send gathering invitations" },
    { phase: "2-3", title: "Draft the gathering seating chart" },
    { phase: "1", title: "Give final gathering count to vendors" },
    { phase: "after", title: "Send thank-you notes (aim for 3 months from the gathering)" },
  ],
};
