import {z} from 'zod';
const n=z.number().finite().min(0).max(100000);const text=z.string().max(2000);
const url=z.string().max(2000000).refine(v=>!v||/^https:\/\//i.test(v)||/^\/api\/uploads\/[a-zA-Z0-9.-]+$/.test(v)||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v),'Use an HTTPS link or uploaded image');
export const dateValue=z.string().refine(v=>!v||/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(`${v}T12:00:00Z`))&&new Date(`${v}T12:00:00Z`).toISOString().startsWith(v),'Use a valid date');
export const objectSchema=z.object({id:z.string().max(100),catalogId:z.string().max(100),name:text,kind:z.enum(['flower','foliage','vessel','candle','plate','glass','napkin','paper','sign','arch','drape','plinth','favor','light']),color:z.string().regex(/^#[0-9a-f]{6}$/i),x:z.number().min(-3000).max(3000),z:z.number().min(-3000).max(3000),y:n.max(1000),rotation:z.number().min(-360).max(360),width:n.min(.1).max(1000),depth:n.min(.01).max(1000),height:n.min(.01).max(1000),count:z.number().int().min(1).max(100),locked:z.boolean(),imageUrl:url.optional(),parentId:z.string().max(100).optional()});
export const designSchema=z.object({version:z.literal(1),revision:z.number().int().min(1),room:z.object({width:n.min(100).max(10000),depth:n.min(100).max(10000),height:n.min(100).max(3000),photo:url,photoScale:n.min(10).max(300),photoX:n.max(100),photoY:n.max(100)}),surface:z.object({shape:z.enum(['round','rectangle','none']),width:n.min(30).max(1000),depth:n.min(30).max(1000),height:n.max(200),linen:z.string().regex(/^#[0-9a-f]{6}$/i),runner:z.string().refine(v=>!v||/^#[0-9a-f]{6}$/i.test(v)),seats:z.number().int().min(0).max(40),linenDrop:n.max(150)}),objects:z.array(objectSchema).max(250),contingency:n.max(1),hoursPerHelper:n.min(.5).max(24),helpers:z.array(z.string().max(100)).max(50),lighting:z.enum(['daylight','evening']),references:z.array(z.object({id:z.string().max(100),url,title:text,imageUrl:url.optional(),note:text,source:z.enum(['upload','pinterest','link','canva'])})).max(60),artwork:z.array(z.object({id:z.string().max(100),name:text,provider:z.string().max(80),designId:z.string().max(100).optional(),editUrl:url,previewUrl:url,fileUrl:url,width:n.min(.1).max(500),height:n.min(.1).max(500),copies:z.number().int().min(1).max(10000),approved:z.boolean(),websiteUrl:url.optional()})).max(60),comments:z.array(z.object({id:z.string().max(100),body:text,author:z.string().max(100),at:z.string().max(40),objectId:z.string().max(100).optional(),resolved:z.boolean()})).max(200),boxes:z.array(z.object({id:z.string().max(100),name:text,destination:text,owner:text,transport:text,after:z.enum(['keep','return','sell','donate']),items:z.array(z.object({materialId:z.string().max(100),qty:n,packed:n,placed:n})).max(250)})).max(100),trials:z.array(z.object({id:z.string().max(100),date:dateValue,photo:url,minutes:n,cost:n,notes:text})).max(30),approval:z.object({status:z.enum(['draft','review','approved']),by:z.string().max(100),at:z.string().max(40)})});
export const materialSchema=z.object({id:z.string().max(100),label:z.string().max(300),qty:n,unit:z.string().max(60),estEach:n,source:z.string().max(200).optional(),fate:z.enum(['buy','rent','own','borrow']),bought:z.boolean(),catalogId:z.string().max(100).optional(),perUnit:n.optional(),packSize:n.min(1).optional(),orderedQty:n.optional(),receivedQty:n.optional(),ownedQty:n.optional(),actualUnitCost:n.optional(),sourceUrl:url.optional(),orderBy:dateValue.optional(),retired:z.boolean().optional()});
export const stepSchema=z.object({id:z.string().max(100),when:z.string().max(100),what:z.string().max(300),hours:n.max(10000),done:z.boolean(),dayOffset:z.number().int().min(-2000).max(365).optional(),dueDate:dateValue.optional(),assignee:z.string().max(100).optional(),instructions:z.array(text).max(30).optional(),dependsOn:z.array(z.number().int().min(0).max(99)).max(50).optional(),hoursMode:z.enum(['fixed','recipe','per-piece']).optional(),perPieceHours:n.optional()});
export const saveSchema=z.object({id:z.string().max(100),expectedVersion:z.number().int().min(0),title:z.string().trim().min(1).max(150),qty:z.number().int().min(1).max(10000),budget:n,note:text,owner:z.string().max(100),zone:z.string().max(200),design:designSchema,materials:z.array(materialSchema).max(500),steps:z.array(stepSchema).max(100),checkpoint:z.string().max(100).optional()});
export const kindSchema=z.enum(['floral','table','print','cricut','decor','lighting','favors']);
export function sameOrigin(request:Request){const origin=request.headers.get('origin');if(!origin)return true;try{const url=new URL(origin);return ['https:','http:'].includes(url.protocol)&&(origin===new URL(request.url).origin||url.host===request.headers.get('host')||origin===process.env.APP_URL);}catch{return false;}}
